title: Furkan Canturk
email: contact@minduniversestudio.com
url: https://minduniversestudio.com
baseurl: ""

markdown: kramdown
permalink: /devlogs/:title/

exclude:
  - Archive/
  - PSD/
  - README.md
  - Furkan_Portfolio_Pack/
  - "Blue Modern Front End Developer Business Card/"
